-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS USERS(
    ID SERIAL PRIMARY KEY,
    LOGIN TEXT NOT NULL,
    PASSWORD TEXT NOT NULL,
    BALANCE FLOAT DEFAULT 0 NOT NULL
);

CREATE TABLE IF NOT EXISTS ORDERS(
    ID SERIAL PRIMARY KEY,
    NUMBER TEXT NOT NULL,
    USER_ID INT NOT NULL,
    UPLOADED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    FOREIGN KEY(USER_ID) REFERENCES USERS(ID),
    OPERATION_TYPE TEXT DEFAULT 'ACCRUAL',
    STATUS TEXT NOT NULL DEFAULT 'NEW',
    AMOUNT FLOAT DEFAULT 0 NOT NULL
);


-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE USERS;
DROP TABLE ORDERS;
-- +goose StatementEnd
