-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS USERS(
    ID SERIAL PRIMARY KEY,
    LOGIN TEXT NOT NULL,
    PASSWORD TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS ORDERS(
    ID SERIAL PRIMARY KEY,
    NUMBER BIGINT UNIQUE NOT NULL,
    USER_ID INT NOT NULL,
    UPLOADED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    FOREIGN KEY(USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE IF NOT EXISTS WITHDRAWALS(
    ORDER_NUMBER BIGINT PRIMARY KEY,
    USER_ID INT NOT NULL,
    AMOUNT FLOAT DEFAULT 0,
    PROCESSED_AT timestamp WITH TIME ZONE DEFAULT NOW(),
    FOREIGN KEY(ORDER_NUMBER) REFERENCES ORDERS(NUMBER),
    FOREIGN KEY(USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE IF NOT EXISTS ACCRUALS
(
    ORDER_NUMBER BIGINT PRIMARY KEY,
    USER_ID INT NOT NULL,
    STATUS TEXT NOT NULL DEFAULT 'NEW',
    AMOUNT FLOAT DEFAULT 0,
    UPLOADED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    FOREIGN KEY (user_id) REFERENCES users (id),
    FOREIGN KEY (ORDER_NUMBER) REFERENCES orders (NUMBER)
);

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE USERS;
DROP TABLE ORDERS;
-- +goose StatementEnd
