-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS USERS(
    ID SERIAL PRIMARY KEY,
    LOGIN TEXT NOT NULL,
    PASSWORD TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS ORDERS(
    ID SERIAL PRIMARY KEY,
    NUMBER BIGINT UNIQUE NOT NULL,
    USER_ID INT NOT NULL,
    STATUS TEXT NOT NULL,
    ACCRUAL INT,
    UPLOADED_AT TIMESTAMP NOT NULL,
    FOREIGN KEY(USER_ID) REFERENCES USERS(ID)
);

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE USERS;
DROP TABLE ORDERS;
-- +goose StatementEnd
